### ISSUE TITLE
Mesh Simplification Implementation Details

### ISSUE THREAD

**Issue by 22TonyFStark** [nissmar/PoNQ#2]
Hello,

I visited the project homepage and noticed that there is a mention of mesh simplification. I am very interested in this feature and would like to learn more about how it is implemented.

Could you please provide a brief overview of the mesh simplification process and how it can be achieved through code? If possible, could you also provide some examples or references to relevant documentation?

Thank you very much for your time and help!

Best regards,
Kinny

**Comment by nissmar** [comment]
Hi Kinny, 

We describe our mesh simplification (dubbed PoNQ lite) in [our paper](https://arxiv.org/pdf/2403.12870) section 4.3. The relevant code can be found [here](https://github.com/nissmar/PoNQ/blob/25037ed9eccc6ad63529c50ca83a70086fceefdd/src/utils/CNN_to_PoNQ_or_lite.py#L34). The core idea is that each surface patch corresponds to a QEM matrix, and the union of N surface patches corresponds to the sum of the N QEM matrices.

Note that the [original QEM article](https://www.cs.cmu.edu/~./garland/Papers/quadrics.pdf) provides more insight on quadric simplification, if you are interested I also highly recommend reading [this one](https://www.graphics.rwth-aachen.de/publication/03308/)

Best, 
Nissim
