### ISSUE TITLE
Watertight check code

### ISSUE THREAD

**Issue by Vincentorick** [nissmar/PoNQ#4]
Could you please provide the code for watertightness checking? Or is it same to the code in VoroMesh?

**Comment by nissmar** [comment]
Hi Vincent, 

The code is provided: https://github.com/nissmar/PoNQ/blob/main/src/eval/check_watertight.py

I just provided the compiled version of 'self_intersect.cpp', but you can also compile it yourself (see README)

**Comment by Vincentorick** [comment]
Thank you so much! This really helps!
